name: datcao
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+15

environment:
  sdk: ">=2.9.2 <3.0.0"

dependencies:
  agora_rtc_engine: ^4.0.6
  animated_theme_switcher: ^2.0.1
  audioplayers: ^0.20.0
  auto_size_text: ^2.1.0
  bot_toast: ^4.0.1
  cached_network_image: ^3.1.0
  cloud_firestore: ^2.5.1
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.3
  dash_chat: ^1.1.16
  device_info: ^2.0.2
  dio: ^4.0.0
  dotted_border: ^2.0.0+1
  expansion_tile_card: ^2.0.0
  file_utils: ^1.0.1
  firebase_auth: ^3.1.0
  firebase_core: ^1.6.0
  firebase_dynamic_links: ^2.0.9
  firebase_messaging: ^10.0.6
  firebase_storage: ^10.0.3
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.1.2
  flutter_callkeep: ^0.1.8
  #flutter_emoji_keyboard: ^0.1.3
  flutter_linkify: ^5.0.2
  overlay_support: ^1.2.1
  flutter_localizations:
    sdk: flutter
  flutter_native_image: ^0.0.6+1
  flutter_staggered_grid_view: ^0.4.0
  flutter_statusbar_text_color: ^0.1.2
  flutter_svg: ^0.22.0
  flutter_tags: ^0.4.9+1
  flutter_typeahead: ^3.2.0
  fluttertoast: ^8.0.8
  font_awesome_flutter: ^9.1.0
  geolocator: ^7.6.0
  google_fonts: ^2.1.0
  google_maps_flutter: ^2.0.8
  graphql: ^5.0.0
  hashtagable: ^2.0.2+1
  html: ^0.15.0
  image: ^3.0.2
  image_picker: ^0.8.4
  intl_phone_number_input: ^0.7.0+2
  inview_notifier_list: ^2.0.0
  material_design_icons_flutter: ^4.0.5955
  material_floating_search_bar: ^0.3.4
  multi_image_picker: ^4.8.1
  open_appstore: ^1.0.2
  package_info: ^2.0.2
  path_provider: ^2.0.3
  permission_handler: ^8.1.4+2
  photo_manager: ^1.3.1
  photo_view: ^0.12.0
  pin_code_fields: ^7.3.0
  provider: ^5.0.0
  readmore: ^2.1.0
  rxdart: ^0.26.0
  sentry: ^6.0.0
  share: ^2.0.4
  shared_preferences: ^2.0.7
  simple_url_preview: ^3.0.1
  skeleton_loader: ^2.0.0+4
  sliding_up_panel: ^2.0.0+1
  timeago: ^3.1.0
  toast: ^0.1.5
  url_launcher: ^6.0.10
  video_player: ^2.1.15
  video_thumbnail: ^0.4.3
  webview_flutter: ^2.0.12
  wifi_info_flutter: ^2.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/logo_datcao.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/
    - assets/language/
    - assets/icon/
    - assets/sound/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-BlackItalic.ttf
        - asset: assets/fonts/Roboto-BoldItalic.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-LightItalic.ttf
        - asset: assets/fonts/Roboto-MediumItalic.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
